In [1]:
import pandas as pd
import numpy as np

In [30]:
data = np.random.uniform(-2 , 2 , size = (6,8))
df = pd.DataFrame(data )
df

# https://www.codegrepper.com/code-examples/python/python+fstring

,0,1,2,3,4,5,6,7
0,-0.719057,-1.427226,0.092920,-1.513302,0.501699,-0.032344,0.809496,1.630693
1,0.060627,1.845326,-1.244052,-0.646792,1.295389,0.324024,1.517578,-1.357283
2,-0.322440,1.158838,0.296819,-0.556579,1.525666,1.033852,0.189367,-1.440268
3,-1.102373,0.722252,1.672365,0.306363,1.647472,0.455757,-0.743033,-1.922184
4,0.916333,-1.301610,0.940713,1.377446,1.938142,1.296328,-1.544654,-0.821843
5,0.727986,0.919669,-0.975083,1.781746,1.638491,-0.847164,0.758838,-1.689786

# Using f-strings to highlight negative values

In [93]:
def negative_color(x):
    if x > 0: 
        color = 'black'
    else: 
        color = 'red'
    
    return f'color: { color }'

In [94]:
df.style.applymap(negative_color)

# To highlight the biggest value in each column

In [82]:
colmax = df.style.highlight_max(color="#CBCE91FF")
colmax

# To highlight the biggest value in entire Dataframe

In [84]:
df.style.highlight_max( axis=None , color="#CBCE91FF")

# To highlight biggest value in each row

In [85]:
rowmax = df.style.highlight_max( axis=1 , color="#CBCE91FF")
rowmax

# Adding Bar plot to pandas DataFrame

In [73]:
df.style.bar(width=90 , color= [ "#EEA47FFF" , "#9CC3D5FF" ], align= "mid" , vmin=(-2) , vmax = (2))

# To change color while hovering

In [66]:
df.style.set_table_styles([{'selector': 'tr:hover','props': [('background-color', 'pink')]}])